// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXmAyZEyx2h16XbM6y7VJj3uspA6V-3o',
    appId: '1:1076536839011:web:82672a1f0677f73abba156',
    messagingSenderId: '1076536839011',
    projectId: 'firstmeal1',
    authDomain: 'firstmeal1.firebaseapp.com',
    storageBucket: 'firstmeal1.appspot.com',
    measurementId: 'G-Q84H4G9WLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHivqkEFFLGYHXY8_6sInBfYfmv_e688A',
    appId: '1:1076536839011:android:3fbd2e082f0e1fa5bba156',
    messagingSenderId: '1076536839011',
    projectId: 'firstmeal1',
    storageBucket: 'firstmeal1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv2qa3S2ik6jYqQkcqstePNx9S_Dj8Fmw',
    appId: '1:1076536839011:ios:83bf47785474e805bba156',
    messagingSenderId: '1076536839011',
    projectId: 'firstmeal1',
    storageBucket: 'firstmeal1.appspot.com',
    iosBundleId: 'com.example.foodPanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv2qa3S2ik6jYqQkcqstePNx9S_Dj8Fmw',
    appId: '1:1076536839011:ios:83bf47785474e805bba156',
    messagingSenderId: '1076536839011',
    projectId: 'firstmeal1',
    storageBucket: 'firstmeal1.appspot.com',
    iosBundleId: 'com.example.foodPanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVXmAyZEyx2h16XbM6y7VJj3uspA6V-3o',
    appId: '1:1076536839011:web:34b25f42ebe8e92fbba156',
    messagingSenderId: '1076536839011',
    projectId: 'firstmeal1',
    authDomain: 'firstmeal1.firebaseapp.com',
    storageBucket: 'firstmeal1.appspot.com',
    measurementId: 'G-33VEXZVKSL',
  );

}